Initial cleanup
Platoniq/decidim-ub pull request #4
Opened 2024-06-26 16:29 UTC by HHassig

Homepage spec
Factories spec
rails helper spec
spec helper

Remove test/ directory

2024-06-26 17:23 UTC, HHassig commented
Unable to get rspec to pass after adding the i18n file

2024-06-26 19:55 UTC, HHassig commented
Skipped "spec/system/homepage_spec.rb: from [https://github.com/Platoniq/decidim-inspire/pull/4/files](url), unsure which version of this file we want in this repo.
rpsec  passes!

2024-06-27 07:37 UTC, fblupi requested changes
I asked @rxnetwalker and he told me the EU logo should not be included in this project.

You should not include the `public/sw.js*` files. Please remove them from this PR and change the `.gitignore` to ignore those files so it won't happen again.

2024-06-27 14:14 UTC, fblupi approved these changes

2024-06-27 14:14 UTC, merged